api_version = "2024-01"

[[extensions]]
type = "theme"
name = "Pixel Tracker"
handle = "pixel-tracker"

[extensions.capabilities]
network_access = true

[[extensions.blocks]]
type = "pixel-tracker"
name = "Pixel Tracker"
target = "@app"

